### ISSUE TITLE
Please license as freedom-respecting software

### ISSUE THREAD

**Issue by strugee** [junaidali/pharos-linux#7]
Currently in most jurisdictions it is actually illegal to use your code due to copyright law. It would be super great if you would relicense this project to be open source/[freedom-respecting software](https://www.gnu.org/philosophy/free-sw.html).

https://choosealicense.com/ can help with this. It also includes [a page](https://choosealicense.com/no-permission/) on why not having a license might not be what you intended.

Thanks!

**Comment by junaidali** [comment]
Thank you for your recommendation. Github did not encourage licensing your project in the past when I first uploaded this project, so never got around to adding it.
